function installClarityStyles() {
  if (document.getElementById('clarityStyles')) return;
  const style = document.createElement('style');
  style.id = 'clarityStyles';
  style.textContent = `
    :root{--egypt-border:linear-gradient(90deg,rgba(0,229,255,.42),rgba(216,200,154,.35),rgba(240,200,80,.72));}
    .weather-foreground-overlay{position:fixed;inset:0;z-index:5;pointer-events:none;overflow:hidden;opacity:.16}.weather-foreground-overlay:before,.weather-foreground-overlay:after{content:'';position:absolute;inset:-20%;pointer-events:none}.weather-foreground-overlay.rain:before,.weather-foreground-overlay.storm:before{background:repeating-linear-gradient(105deg,rgba(0,229,255,0) 0 24px,rgba(0,229,255,.24) 25px,rgba(0,229,255,.24) 27px,rgba(0,229,255,0) 31px);filter:blur(.25px);animation:fgRainReadable .9s linear infinite}.weather-foreground-overlay.rain:after,.weather-foreground-overlay.storm:after{background:repeating-linear-gradient(105deg,rgba(244,234,208,0) 0 56px,rgba(244,234,208,.16) 57px,rgba(244,234,208,.16) 59px,rgba(244,234,208,0) 63px);filter:blur(.4px);animation:fgRainReadable 1.35s linear infinite}.weather-foreground-overlay.storm{opacity:.2}.weather-foreground-overlay.snow:before{background-image:radial-gradient(circle,rgba(244,234,208,.78) 1px,transparent 1.6px),radial-gradient(circle,rgba(244,234,208,.5) 1px,transparent 1.7px);background-size:36px 36px,58px 58px;animation:fgSnow 9s linear infinite}.weather-foreground-overlay.clear:before{background:radial-gradient(circle at 82% 12%,rgba(240,200,80,.18),rgba(240,200,80,.05) 18%,transparent 40%);animation:fgSun 5s ease-in-out infinite}.weather-foreground-overlay.cloudy:before{background:radial-gradient(ellipse at 20% 12%,rgba(216,200,154,.07),transparent 36%),radial-gradient(ellipse at 82% 10%,rgba(216,200,154,.06),transparent 42%);animation:fgCloud 14s ease-in-out infinite}@keyframes fgRainReadable{to{transform:translate3d(-32px,118px,0)}}@keyframes fgSnow{to{background-position:0 130px,45px 190px}}@keyframes fgSun{50%{opacity:.55;transform:scale(1.03)}}@keyframes fgCloud{50%{transform:translateX(3%)}}
    .hub-container,.clock-card,.sky-brief,.signal-card,.metric-card,.rune,.celestial-times,.minutely-precip,.radar-chamber{backdrop-filter:blur(5px);-webkit-backdrop-filter:blur(5px);box-shadow:inset 0 0 0 1px rgba(216,200,154,.05),inset 0 0 26px rgba(240,200,80,.035)!important}.signal-card,.sky-brief,.minutely-precip,.celestial-times,.metric-card,.rune,.radar-chamber{border-image:var(--egypt-border) 1!important}.main-display{margin-top:10px;margin-bottom:20px}.temp-block{padding-top:4px}.conditions-text{margin-top:14px}.wind-rose{display:none!important}.cluster{justify-content:center;margin-top:12px}.wind-speed{margin-top:8px;text-align:center;display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;line-height:1.15}.wind-flow{display:inline-flex;align-items:center;justify-content:center;width:25px;height:25px;border:1px solid rgba(0,229,255,.56);border-radius:999px;color:var(--teal);filter:drop-shadow(0 0 6px rgba(0,229,255,.38));font-size:1rem;transform-origin:center;flex:0 0 auto}.wind-from{color:var(--papyrus);font-size:.58rem;letter-spacing:1px;white-space:nowrap}.day-range-bar{height:5px!important;background:rgba(216,200,154,.18)!important}.day-range-fill{opacity:.85;border-radius:999px!important}.day-legend,.radar-loop-note,.pressure-help{color:#c9bb91;font-size:.56rem;line-height:1.35;letter-spacing:.7px}.day-legend{margin:-2px 0 8px;text-align:center;text-transform:uppercase}.day-legend strong,.pressure-help strong{color:var(--gold2);font-weight:600}.radar-body::after{display:none!important}.radar-loop-ui{margin-top:10px;padding-top:11px;border-top:1px solid rgba(216,200,154,.16)}.radar-loop-label{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;color:var(--papyrus);font-size:.5rem;letter-spacing:.8px;text-transform:uppercase;margin-bottom:7px;text-align:center}.radar-loop-track-real{position:relative;height:5px;border-radius:999px;background:rgba(216,200,154,.18);overflow:hidden}.radar-loop-track-real i{position:absolute;inset:0 auto 0 0;width:28%;border-radius:999px;background:linear-gradient(90deg,var(--teal),var(--gold2));animation:clarityRadarSweep 4.2s ease-in-out infinite}@keyframes clarityRadarSweep{0%{transform:translateX(-110%)}100%{transform:translateX(440%)}}.pressure-help{margin-top:5px}.build-visible{opacity:.85;color:var(--teal2)!important}
  `;
  document.head.appendChild(style);
}

function getWindDirectionLabel(deg){const dirs=['N','NE','E','SE','S','SW','W','NW'];return dirs[Math.round((((deg%360)+360)%360)/45)%8];}
function readWindDegrees(){const raw=document.getElementById('windNeedle')?.style?.transform||'';const match=raw.match(/rotate\(([-0-9.]+)deg\)/);return match?Number(match[1]):0;}
function ensureForegroundWeather(){let overlay=document.getElementById('weatherForegroundOverlay');if(!overlay){overlay=document.createElement('div');overlay.id='weatherForegroundOverlay';overlay.className='weather-foreground-overlay clear';document.body.appendChild(overlay);}const state=document.body.dataset.weatherState||'clear';overlay.className=`weather-foreground-overlay ${state}`;}
function patchWindArrow(){const wind=document.getElementById('windSpeed');if(!wind)return;const degFrom=readWindDegrees();const degTo=(degFrom+180)%360;const fromLabel=getWindDirectionLabel(degFrom);const speedMatch=wind.textContent.match(/(\d+(?:\.\d+)?)\s*mph/i);const speed=speedMatch?`${Math.round(Number(speedMatch[1]))} mph`:'— mph';wind.innerHTML=`<span class="wind-flow" style="transform:rotate(${degTo}deg)">↑</span><span>${speed}</span><span class="wind-from">FROM ${fromLabel}</span>`;}
function patchDayLegend(){const label=[...document.querySelectorAll('.strip-label')].find(el=>el.textContent.toLowerCase().includes('7-day'));if(!label||document.getElementById('dayLegend'))return;const legend=document.createElement('div');legend.id='dayLegend';legend.className='day-legend';legend.innerHTML='<strong>Bar = daily high warmth</strong> — numbers show low/high';label.insertAdjacentElement('afterend',legend);}
function normalizeDailyRails(){const rows=[...document.querySelectorAll('.day-row')];const highs=rows.map(row=>{const txt=row.querySelector('.day-high')?.textContent||'';return Number((txt.match(/-?\d+/)||[])[0]);}).filter(n=>Number.isFinite(n));if(!highs.length)return;const min=Math.min(...highs);const max=Math.max(...highs);const span=Math.max(1,max-min);rows.forEach(row=>{const high=Number(((row.querySelector('.day-high')?.textContent||'').match(/-?\d+/)||[])[0]);const fill=row.querySelector('.day-range-fill');if(!fill||!Number.isFinite(high))return;const pct=42+((high-min)/span)*58;fill.style.left='0%';fill.style.width=`${Math.round(pct)}%`;});}
function patchRadarTimeline(){const body=document.querySelector('.radar-body');if(!body||document.getElementById('radarLoopUI'))return;const ui=document.createElement('div');ui.id='radarLoopUI';ui.className='radar-loop-ui';ui.innerHTML=`<div class="radar-loop-label"><span>Recent</span><span>Moving</span><span>Latest</span><span>Now</span></div><div class="radar-loop-track-real"><i></i></div><div class="radar-loop-note">Radar is an embedded recent-loop view. Use motion direction for the read; exact frame timestamps inside the radar are the source of truth.</div>`;const status=body.querySelector('.radar-status');if(status)status.insertAdjacentElement('afterend',ui);else body.appendChild(ui);}
function patchPressureHelp(){const pressure=document.getElementById('pressureValue');if(!pressure||document.getElementById('pressureHelp'))return;const help=document.createElement('div');help.id='pressureHelp';help.className='pressure-help';help.innerHTML='<strong>hPa</strong> = air pressure. Around 1013 is typical sea-level pressure; falling can mean changing weather.';pressure.insertAdjacentElement('afterend',help);}
function patchBuildStamp(){const stamp=document.getElementById('buildStamp');if(stamp){stamp.textContent='BUILD egypt-1';stamp.classList.add('build-visible');}}
function runClarityPass(){installClarityStyles();ensureForegroundWeather();patchWindArrow();patchDayLegend();normalizeDailyRails();patchRadarTimeline();patchPressureHelp();patchBuildStamp();}
window.addEventListener('load',()=>{setTimeout(runClarityPass,700);setInterval(runClarityPass,2200);});
